- name: "add apt repository for haproxy"
  become: yes
  apt_repository:
    repo: 'ppa:vbernat/haproxy-1.8'

- name: "install package haproxy"
  become: yes
  apt:
    name: haproxy
    update_cache: yes


