- hosts: kdev
  remote_user: vagrant
  serial: 1
  roles:
    - base
    - git
    - ansible
    - aws-cred
    - terraform
    - docker
    - docker-compose
#    - etcd
#    - flannel
#    - k8s-base
#    - k8s-master
