---
- name: restart ntp
  become: true
  become_method: sudo
  service: 
    name=ntp
    state=restarted
- name: force ntp update
  become: true
  become_method: sudo
  shell: "systemctl stop ntp && ntpd -gq && systemctl start ntp"

