---
- name: Ensure git repos directory
  become: yes
  file:
    path: "~/repos"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: "Add jmq gihub private key to .ssh dir"
  copy:
    src: /home/keys/jmquint_github_rsa
    dest: "~/.ssh"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0600

- name: "Add jmq gihub public key to .ssh dir"
  copy:
    src: /home/keys/jmquint_github_rsa.pub
    dest: "~/.ssh"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0600

- name: "Add ssh config file to .ssh dir"
  copy:
    src: /home/keys/config
    dest: "~/.ssh"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0600

- name: "Add github identityfile to .ssh/config file"
  lineinfile:
    path: "~/.ssh/config"
    insertbefore: '^Host *'
    line: "IdentityFile ~/.ssh/jmquint_github_rsa"

# - name: "Clone repo ansible but do not update if it exists"
#   git:
#     repo: ssh://github.com/jmquint/ansible.git
#     dest: "~/repos"
#     update: no

# - name: "Clone repo terraform-aws but do not update if it exists"
#   git:
#     repo: ssh://github.com/jmquint/terraform-aws.git
#     dest: "~/repos"
#     update: no

