---
# - name: Ensure tmp dir for terraform installation
#   file:
#     path: /home/vagrant/.terraform_tmpdir
#     state: directory

- name: Download terraform binary package and unzip
  become: yes
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.10.8/terraform_0.10.8_linux_amd64.zip?_ga=2.9202421.1326352719.1509200094-287124648.1508689087 
    dest: /usr/local/bin
    remote_src: yes

# Add terraform key + fichiers terraform
- name: Ensure terraform directory
  become: yes
  file:
    path: /home/vagrant/terraform
    state: directory
    owner: vagrant
    group: vagrant


- name: Copy terraform aws SSH Key Files
  become: yes
  copy:
    src: /home/keys/{{ item }}
    dest: /home/vagrant/.ssh/{{ item }}
    owner: vagrant
    group: vagrant
    mode: 0600
  with_items:
    - terraform.pem
    - terraform.pub

