---
- name: Add list of ansible hosts file to /etc/ansible/hosts
  become: yes
  blockinfile:
    block: "{{ lookup('file', '/home/shared/ansible-hosts') }}"
    dest: "~/.bashrc"
    backup: yes
#  assemble:
#    src: /home/shared/ansible-hosts
#    dest: /etc/ansible/hosts



