---
- name: Loads docker apt-key 
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ensure Docker  Repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Ensure docker required packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Run the equivalent of apt-get update
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 86400


- name: Ensure docker package
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-ce

- name: Ensure Docker Group
  group:
    name: docker
    state: present

- name: Ensure User in Docker Group
  become: yes
  user:
    name="{{ ansible_user_id }}"
    groups=docker
    append=yes

